#!/usr/bin/env python

import os
import shutil
import torch
from diffusers import (
    KandinskyImg2ImgPipeline,
    KandinskyPriorPipeline,
    KandinskyPipeline,
    DiffusionPipeline,
)


MODEL_CACHE = "model_cache"


#if os.path.exists(MODEL_CACHE):
#    shutil.rmtree(MODEL_CACHE)
os.makedirs(MODEL_CACHE, exist_ok=True)


pipe_prior = DiffusionPipeline.from_pretrained(
    "kandinsky-community/kandinsky-2-2-prior",
    cache_dir=MODEL_CACHE,
    torch_dtype=torch.bfloat16,
).to("cpu", torch.bfloat16)


t2i_pipe = DiffusionPipeline.from_pretrained(
    "kandinsky-community/kandinsky-2-2-decoder",
    cache_dir=MODEL_CACHE,
    torch_dtype=torch.bfloat16,
).to("cpu", torch.bfloat16)

# save to disk
save_dir = "model_cache_fp16"
t2i_pipe.save_pretrained("save_dir/decoder")
pipe_prior.save_pretrained("save_dir/prior")
